### PR TITLE
Creator: Publish submission window

### LINKED ISSUE #60: Pattern submission details
When a user goes to submit a pattern, they will get a modal with 3 "steps" (2 + done).

Step-1

Step-2

Done

It should be pre-filled with any meta information they entered in the pattern sidebar. Clicking Publish will call the API to save the post. Tracking validation & post-save is in #36

### PR DESCRIPTION
**Pull request by StevenDufresne**
This adds a window to retrieve pattern information and save it to the pattern directory. This will remain incomplete until the following is added:
- Connect it to the editor
- Add link URL to success confirmation (currently unknown)

Fixes #60

### Example Usage
```
<PublishModal  
    isSubmitted={ true/false } // If true, shows the save success confirmation window
    onSubmit={ () => savePost() }
    onClose={ () => setShowModal( false ) }
/>
```

### Screenshots

| View 1 | View 2 | Confirmation |  GIF |
| --- | --- |  --- | --- |
|  |  |   |  |

### CODE REVIEW

**Comment by ryelle** [comment]
@StevenDufresne Did you want me to review this now, or wait for #115 to wrap up?

**Comment by StevenDufresne** [comment]
> @StevenDufresne Did you want me to review this now, or wait for #115 to wrap up?

It's up to you. Technically the component code is ready for review, but you'll need to manually include the component to get it to show up so you can see it.

**Comment by ryelle** [comment]
Can you update the testing instructions with what you mean?

**Comment by StevenDufresne** [comment]
> Can you update the testing instructions with what you mean?

There's too much to do to test. Let's wait until we have a `pattern-creator` to tie into.

**Comment by ryelle** [comment]
Works for me -- I switched this back to a draft PR, when 115 is merged and it's ready for review, you can mark it ready & re-request my review.

**Comment by StevenDufresne** [comment]
@ryelle I think this is ready for review, or at least I need some support to get this in.

**Review by ryelle — APPROVED** [review]
Up to date with trunk now, looks good to merge

**Pull request merged**
